resources:
  - ../../base

namespace: staging

patches:
  - target:
      kind: Deployment
      name: hello
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

images:
  - name: nginx
    newTag: "1.25.3"
